services:
  backend:
    build:
      context: ./back-end
    container_name: curd-backend
    env_file:
      - ./back-end/.env
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
    container_name: curd-frontend
    ports:
      - "8000:80" 
    depends_on:
      - backend