services:
  backend:
    build:
      context: ./back-end
    image: curd-backend:1.0.0
    container_name: curd-backend
    env_file:
      - ./back-end/.env
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
    image: curd-frontend:1.0.0
    container_name: curd-frontend
    ports:
      - "8000:80" 
    depends_on:
      - backend